Add symbolic interpolation operator: `Interp`
firedrakeproject/ufl pull request #26
Opened 2021-12-06 09:02 UTC by nbouziani

This PR builds on the dual space changes recently introduced  (#21, #25) and introduces the symbolic interpolation operator (`ufl.Interp`). This PR prepares the ground for operators that can be seen as operators and as forms such as `Interp` or `ExternalOperator`. Most of the bits in this PR come from the `ExternalOperator` dual branch which will come in another PR.

For example, let `I(u, V2)` be the interpolation of the coefficient `u \in V1` into the function space `V2`, where `I` refers to the interpolation operator `I: V1 -> V2`. `I` can also be seen as a form using the reflexivity of `V2`. That is, we have `I: V1 x V2^{*} -> R` where `I` is linear with respect to both entries, we use the notation `I(u, v^*)` where `v^*` is a `Coargument` in `V2`

Main components of this PR:

### Add `BaseFormOperator`:

We introduce the so-called `BaseFormOperator` class which accounts for operators than can also be seen as forms such as `Interp` or `ExternalOperator`.

### Add `Interp`:

Add the `Interp` class which we refer to as the symbolic interpolation operator.

### Add differentiation mechanisms for `BaseFormOperator` objects and Interp differentiation:

1.  Add a `BaseFormOperatorDerivative` node

2. Add differentiation (2 stages mechanism) for base form operators:
        `dF(u, I(u, v^{*}); v)/du [uhat] = \partial F/\partial u + Action(dF/dI, dI/du)`
which works by:

- Applying differentiation by traversing the DAG and whenever we see a BaseFormOperator, we return 0 and record the operations, i.e. instead of returning `dF/du` we return `\partial F/\partial u`.

- Applying chain rule on the recorded operations, i.e. add terms like `Action(dF/dI, dI/du)` for all the base form operators that got recorded.

3. Add `Interp` differentiation: `dI(u, v*)/du [uhat] = I(uhat, v*)` (by linearity).
4. Add `replace_derivative_nodes` algorithm for replacing derivative nodes.

### Update `analysis.py`

2021-12-15 16:57 UTC, dham requested changes

2021-12-15 16:57 UTC, dham commented on ufl/core/base_form_operator.py
> +    _ufl_noslots_ = True
????

2023-06-13 14:45 UTC, dham commented on ufl/core/interp.py
> +        if not isinstance(other, Interp):
```suggestion
        if type(other) == Interp:
```

2023-09-11 14:50 UTC, nbouziani commented on ufl/core/base_form_operator.py
> +
Deprecated feature to be removed

2023-09-11 14:50 UTC, nbouziani commented on ufl/core/base_form_operator.py
> +        return result_coefficient
Remove

2023-09-11 14:50 UTC, nbouziani commented on ufl/core/interp.py
> +        result_coefficient = result_coefficient or self._result_coefficient
Deprecated feature to be removed

2023-09-11 14:50 UTC, nbouziani commented on test/test_duals.py
> +    assert dAcdu == action(adjoint(derivative(w, u)), u) + action(w, derivative(u, u))
Lift that to dualspace

2023-09-11 14:50 UTC, nbouziani commented on test/test_duals.py
> +    assert dAcdu == Action(w, v)
Lift that to dualspace

2023-09-11 14:50 UTC, nbouziani commented on test/test_interp.py
> +    # assert extract_arguments_and_coefficients(Iu) == ([vstar], [u, Iu.result_coefficient()])
Remove spurious comments

2023-09-11 14:50 UTC, nbouziani commented on ufl/algorithms/apply_derivatives.py
> +        # TODO: Should we use `derivative` here to take into account Extop/Interp node?
Remove spurious comment (answer is no)

2023-09-11 14:50 UTC, nbouziani commented on ufl/core/base_form_operator.py
> +            function_space = FunctionSpace(domain, element)
Remove

2023-09-11 14:50 UTC, nbouziani commented on ufl/core/base_form_operator.py
> +        return self.result_coefficient()._count
Deprecated features: that shouldn't be needed anymore

2023-09-11 14:50 UTC, nbouziani commented on ufl/core/base_form_operator.py
> +
Remove: `result_coefficient` is deprecated

2023-09-11 14:50 UTC, nbouziani commented on ufl/formoperators.py
> +            pass
Remove since `Adjoint` differentiation, which is the reason motivating that bit, is not supported anymore

2023-09-12 14:08 UTC, nbouziani commented on ufl/core/base_form_operator.py
> +        from ufl.algorithms.analysis import extract_arguments, extract_coefficients, extract_type
Import cycle issue

2023-09-12 17:30 UTC, closed without merging